### ISSUE TITLE
Fix observer mode

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/cncnet-ladder-api#269]
Testing from [FC]Matt:

**RA2:**
-Seems Good ✅ 

**YR:** 
- If observers queue as Soviet, Supers are on in AvY games
- If observers queue as Allies, there is a chance (happened once) that Yuri cannot build supers and Allies can). This game reconned about 6 minutes in

**RA2 Clan Ladder:**
- Almost~90% of the time recons between 3-4 minutes into the game. No apparent cause. Happens on different maps, different Obs faction, and different player-faction combinations

**Misc:**
- It seems 2 observers can match with a single player (happened with me and Doofus) . Can't remember which ladder this was in, probably RA2, but expect it can happen across all ladders

**Comment by rohsyl** [comment]
should be fixed in future release
