### ISSUE TITLE
Is this still in active development?

### ISSUE THREAD

**Issue by webdevhayes** [CnCNet/cncnet-ladder-api#57]
Hello,

I was just wondering if this is in active development and what the plans are for this? 

I came across this and thought I could maybe contribute to this. I just want to know if this is worth my time?

**Comment by GrantBartlett** [comment]
👋 I would chat in the Developers Discord channel on what you would want to help out on https://cncnet.org/discord

**Comment by alexp8** [comment]
Yeah @webdevhayes feel free to join the Discord and share your thoughts/plans
